### ISSUE TITLE
cgrep doesn't build with Clang 10 (depending on how it is packaged)

### ISSUE THREAD

**Issue by schra** [terminaldweller/cgrep#14]
On operating systems such as Arch Linux, the libclang libraries of Clang 10 are package differently now.

See https://www.archlinux.org/todo/llvm-10/:

> All of clang's C++ API is now shipped as `libclang-cpp.so` instead of
> the numerous component libraries we had before. This change will
> require patching in most packages to use the new library name. Look
> for upstream commits that support the new library; if that fails,
> Fedora and/or Gentoo should have patches for this.

This essentially means that it's not possible to build cgrep on Arch Linux now. For the AUR package I maintain I created a simple patch file that fixes this problem: https://github.com/schra/pkgbuilds/blob/d551ebc734a02f3418ff0df58a25d314cb973084/cgrep-clang/adjust-libclang-lib-names.patch

I think a proper fix would check if the library `libclang-cpp` exists. If yes, use it. If no, use the smaller libraries as done before.

Btw, Ubuntu ships both libclang-cpp.so.10 and also the smaller libraries.

**Comment by terminaldweller** [comment]
Thanks for letting me know. I guess I should finally switch to cmake.

**Comment by terminaldweller** [comment]
I added a new branch. It's called `cmake`. The cmake works fine if `llvm-config` is named llvm-config, without any numbers. I'll fix the llvm-config name issue and add install supports in the next couple of days.
P.S.: learning cmake wasn't exactly a piece of cake. took me 8 hours to write that thing...

**Comment by schra** [comment]
Sounds good :)

>  P.S.: learning cmake wasn't exactly a piece of cake. took me 8 hours to write that thing...

Yeah I feel you

**Comment by terminaldweller** [comment]
The cmake branch is now funcitonal. to build you just need to do(assuming you're doing an out-of-source build):<br/> 
```bash
cmake ../ -DLLVM_CONF=llvm-config-10 -DCMAKE_CXX_COMPILER=clang++-10 -DUSE_MONOLITH_LIBTOOLING=ON
```
I still need to add some extra stuff in there to make my life easier developing cgrep. When I get around to doing that, I'll just merge the cmake branch wiht master.
