### ISSUE TITLE
clang:12 support.

### ISSUE THREAD

**Issue by bartoszek** [terminaldweller/cgrep#18]
Any chance for update to `clang:12` ?

**Comment by terminaldweller** [comment]
sure. give me 24 hours.

**Comment by bartoszek** [comment]
Shit, waiting :feelsgood:

**Comment by terminaldweller** [comment]
i just added the fix for llvm 12 and 13 to master. once i figure out what's wrong with travis.com, i'll add llvm 12 and 13 to the test matrix and push a new release. then i'll close this.
let me know if there's anything else wrong.

**Comment by terminaldweller** [comment]
its done.

**Comment by bartoszek** [comment]
Works great, thanks.
