### ISSUE TITLE
Match named fields inside structs initialization

### ISSUE THREAD

**Issue by phsilva** [terminaldweller/cgrep#9]
Have a use case that I am not sure `cgrep` already supports.

I am working on some `CPython` code and wanted to find all places in my code where variables of a given type and print the value of a struct field in those variables.

Concrete example:

CPython has a `PyModuleDef` struct with a field named [`m_slots`](https://docs.python.org/3/c-api/module.html#c.PyModuleDef.m_slots). I need to find all variables that value m_slots and set it to NULL.

Was considering using `clang-query` but looks like something `cgrep` could handle.

What do you think?

**Comment by terminaldweller** [comment]
You can use `cgrep`'s `--memvar` switch to search for `m_slots`, but it will match any `fieldDecl` that is named `m_slots`, not just the ones in `PyModuleDef`.

**Comment by phsilva** [comment]
Yes, that should be enough for now, hopefully, the field name is quite unique.

I was looking for a solution like Structural Search and Replace from Jetbrains IDEs which probably allows something like this (but not for C/C++ at moment).

Thanks anyway, awesome work!

**Comment by terminaldweller** [comment]
now that you mention it, have you looked at clang-refactor? It's part of clang extra tools. I think it should be able to do something like that.
Also on `cgrep`, you can make a new issue and ask this as a new feature.

**Comment by phsilva** [comment]
@bloodstalker No, but I've tried `clang-query`, somewhat similar to `cgrep`. Will look at `clang-refactor`, thanks!

**Comment by terminaldweller** [comment]
`clang-query` is mostly there to reduce the pain of developing ASTmatchers. It's not really geared towards this kind of use.
you're welcome!

**Comment by terminaldweller** [comment]
I'll go ahead and close this. Feel free to re-open if need be,
